[mypy]
python_version = 3.12
strict = False
mypy_path = src

[mypy-faster_whisper.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True

[mypy-qdrant_client.*]
ignore_missing_imports = True

[mypy-paramiko.*]
ignore_missing_imports = True