from __future__ import annotations

from typing import Any, Dict, Protocol


class StoragePort(Protocol):
    def transcript_exists(self, call_id: str) -> bool: ...
    def analysis_exists(self, call_id: str) -> bool: ...
    def load_transcript(self, call_id: str) -> Dict[str, Any]: ...
    def load_analysis(self, call_id: str) -> Dict[str, Any]: ...
    def save_transcript(self, call_id: str, data: Dict[str, Any]) -> None: ...
    def save_analysis(self, call_id: str, data: Dict[str, Any]) -> None: ...
    def ensure_ready(self) -> None: ...
    def close(self) -> None: ...