from __future__ import annotations

from typing import Any, Dict, Protocol


class StoragePort(Protocol):
    def transcript_exists(self, call_id: str) -> bool: ...
    def analysis_exists(self, call_id: str) -> bool: ...
    def load_transcript(self, call_id: str) -> Dict[str, Any]: ...
    def load_analysis(self, call_id: str) -> Dict[str, Any]: ...
    def save_transcript(self, call_id: str, data: Dict[str, Any]) -> None: ...
    def save_analysis(self, call_id: str, data: Dict[str, Any]) -> None: ...
    def mark_analysis_stale_if_text_changed(self, call_id: str, text_sha256: str) -> bool: ...
    def promote_stt_result(self, call_id: str, transcript: Dict[str, Any], *, stt_run_id: str, stt_config_hash: str, source_text_sha256: str) -> None: ...
    def ensure_ready(self) -> None: ...
    def close(self) -> None: ...